name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  http: ^1.4.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  image_picker: ^1.2.0
  file_picker: ^10.3.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/font/
    - assets/random.json

  fonts:
    - family: Cafe24 Oneprettynight
      fonts:
        - asset: assets/font/Cafe24Oneprettynight.ttf
    - family: NanumMyeongjo
      fonts:
        - asset: assets/font/NanumMyeongjo.ttf



